# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json

from pyrogram import Client
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


api_id = 9198879
api_hash = "fedc8935a5d92e73f2d83696a5cceca6"

class Ui_Tg_panel(object):
    def setupUi(self, Tg_panel):

        Tg_panel.setObjectName("Tg_panel")
        Tg_panel.resize(390, 266)

        self.centralwidget = QtWidgets.QWidget(Tg_panel)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 431, 311))
        self.tabWidget.setObjectName("tabWidget")


        self.Tab = QtWidgets.QWidget()
        self.Tab.setObjectName("Tab")

        self.start_spam = QtWidgets.QPushButton(self.Tab)
        self.start_spam.setGeometry(QtCore.QRect(10, 200, 371, 23))
        self.start_spam.setObjectName("start_spam")

        self.sort_chats = QtWidgets.QPushButton(self.Tab)
        self.sort_chats.setGeometry(QtCore.QRect(200, 140, 181, 23))
        self.sort_chats.setObjectName("sort_chats")

        self.otpiska = QtWidgets.QPushButton(self.Tab)
        self.otpiska.setGeometry(QtCore.QRect(10, 140, 181, 23))
        self.otpiska.setObjectName("otpiska")

        self.podpiska = QtWidgets.QPushButton(self.Tab)
        self.podpiska.setGeometry(QtCore.QRect(10, 170, 181, 23))
        self.podpiska.setObjectName("podpiska")

        self.label_7 = QtWidgets.QLabel(self.Tab)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_7.setObjectName("label_7")

        self.sum_podpis = QtWidgets.QLabel(self.Tab)
        self.sum_podpis.setGeometry(QtCore.QRect(110, 10, 161, 16))
        self.sum_podpis.setObjectName("sum_podpis")

        self.label_11 = QtWidgets.QLabel(self.Tab)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_11.setObjectName("label_11")

        self.time_of_work = QtWidgets.QLabel(self.Tab)
        self.time_of_work.setGeometry(QtCore.QRect(90, 30, 101, 16))
        self.time_of_work.setObjectName("time_of_work")

        self.label_13 = QtWidgets.QLabel(self.Tab)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_13.setObjectName("label_13")

        self.label_14 = QtWidgets.QLabel(self.Tab)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_14.setObjectName("label_14")

        self.sum_bots_1 = QtWidgets.QLabel(self.Tab)
        self.sum_bots_1.setGeometry(QtCore.QRect(110, 50, 101, 16))
        self.sum_bots_1.setObjectName("sum_bots_1")

        self.sum_chat_in_bots = QtWidgets.QLabel(self.Tab)
        self.sum_chat_in_bots.setGeometry(QtCore.QRect(110, 70, 101, 16))
        self.sum_chat_in_bots.setObjectName("sum_chat_in_bots")

        self.label_9 = QtWidgets.QLabel(self.Tab)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_9.setObjectName("label_9")

        self.unsuc_mess = QtWidgets.QLabel(self.Tab)
        self.unsuc_mess.setGeometry(QtCore.QRect(140, 90, 141, 16))
        self.unsuc_mess.setObjectName("unsuc_mess")

        self.guide = QtWidgets.QPushButton(self.Tab)
        self.guide.setGeometry(QtCore.QRect(200, 170, 181, 23))
        self.guide.setObjectName("guide")

        self.suc_mess = QtWidgets.QLabel(self.Tab)
        self.suc_mess.setGeometry(QtCore.QRect(170, 110, 181, 16))
        self.suc_mess.setObjectName("suc_mess")

        self.label_20 = QtWidgets.QLabel(self.Tab)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 161, 16))
        self.label_20.setObjectName("label_20")

        ####

        self.tabWidget.addTab(self.Tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.send_num = QtWidgets.QPushButton(self.tab_2)
        self.send_num.setGeometry(QtCore.QRect(10, 200, 171, 23))
        self.send_num.setObjectName("send_num")

        self.send_pass = QtWidgets.QPushButton(self.tab_2)
        self.send_pass.setGeometry(QtCore.QRect(200, 200, 171, 23))
        self.send_pass.setObjectName("send_pass")

        self.phone_number = QtWidgets.QLineEdit(self.tab_2)
        self.phone_number.setGeometry(QtCore.QRect(100, 10, 113, 20))
        self.phone_number.setObjectName("phone_number")

        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_2.setObjectName("label_2")

        self.pass_phone = QtWidgets.QLineEdit(self.tab_2)
        self.pass_phone.setGeometry(QtCore.QRect(120, 50, 91, 20))
        self.pass_phone.setObjectName("pass_phone")

        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 131, 16))
        self.label_3.setObjectName("label_3")

        self.guide_bots = QtWidgets.QPushButton(self.tab_2)
        self.guide_bots.setGeometry(QtCore.QRect(10, 170, 361, 23))
        self.guide_bots.setObjectName("guide_bots")

        self.sum_bots_2 = QtWidgets.QLabel(self.tab_2)
        self.sum_bots_2.setGeometry(QtCore.QRect(150, 140, 101, 16))
        self.sum_bots_2.setObjectName("sum_bots_2")

        ####

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.add_chats = QtWidgets.QPushButton(self.tab_3)
        self.add_chats.setGeometry(QtCore.QRect(10, 200, 361, 23))
        self.add_chats.setObjectName("add_chats")

        self.chats_form = QtWidgets.QPlainTextEdit(self.tab_3)
        self.chats_form.setGeometry(QtCore.QRect(10, 10, 361, 121))
        self.chats_form.setObjectName("chats_form")

        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 141, 16))
        self.label_5.setObjectName("label_5")

        self.guide_chats = QtWidgets.QPushButton(self.tab_3)
        self.guide_chats.setGeometry(QtCore.QRect(10, 170, 361, 23))
        self.guide_chats.setObjectName("guide_chats")

        self.sum_chat_bd = QtWidgets.QLabel(self.tab_3)
        self.sum_chat_bd.setGeometry(QtCore.QRect(160, 140, 101, 16))
        self.sum_chat_bd.setObjectName("sum_chat_bd")

        self.tabWidget.addTab(self.tab_3, "")
        Tg_panel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Tg_panel)
        self.statusbar.setObjectName("statusbar")

        Tg_panel.setStatusBar(self.statusbar)

        self.retranslateUi(Tg_panel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Tg_panel)

        self.add_functions()

    def add_functions(self):
        # Кнопки вкладки "Панель"
        self.start_spam.clicked.connect(self.btn_start_spam)
        self.sort_chats.clicked.connect(self.btn_sort_chats)
        self.otpiska.clicked.connect(self.btn_otpiska)
        self.podpiska.clicked.connect(self.btn_podpiska)
        self.guide.clicked.connect(self.btn_guide)

        # Кнопки вкладки "Боты"
        self.send_num.clicked.connect(self.btn_send_num)
        self.send_pass.clicked.connect(self.btn_send_pass)
        self.guide_bots.clicked.connect(self.btn_guide_bots)

        # Кнопки вкладки "Чаты"
        self.add_chats.clicked.connect(self.btn_add_chats)
        self.guide_chats.clicked.connect(self.btn_guide_chats)

    def retranslateUi(self, Tg_panel):
        _translate = QtCore.QCoreApplication.translate
        Tg_panel.setWindowTitle(_translate("Tg_panel", "Админ-панель"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab), _translate("Tg_panel", "Панель"))
        self.start_spam.setText(_translate("Tg_panel", "Запустить спам"))
        self.sort_chats.setText(_translate("Tg_panel", "Распределить чаты"))
        self.otpiska.setText(_translate("Tg_panel", "Отписаться от всех чатов"))
        self.podpiska.setText(_translate("Tg_panel", "Запустить подписку на чаты"))
        self.guide.setText(_translate("Tg_panel", "Помощь"))

        self.label_7.setText(_translate("Tg_panel", "Подписок на чаты:"))
        self.label_11.setText(_translate("Tg_panel", "Время работы:"))
        self.label_13.setText(_translate("Tg_panel", "Количество ботов:"))
        self.label_14.setText(_translate("Tg_panel", "Количество чатов:"))
        self.label_9.setText(_translate("Tg_panel", "Неудачных сообщений:"))
        self.label_20.setText(_translate("Tg_panel", "Всего отправлено сообщений:"))

        self.sum_podpis.setText(_translate("Tg_panel", "0"))
        self.time_of_work.setText(_translate("Tg_panel", "0"))
        self.sum_bots_1.setText(_translate("Tg_panel", "0"))
        self.sum_chat_in_bots.setText(_translate("Tg_panel", "0"))
        self.unsuc_mess.setText(_translate("Tg_panel", "0"))
        self.suc_mess.setText(_translate("Tg_panel", "0"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Tg_panel", "Боты"))
        self.send_num.setText(_translate("Tg_panel", "Отправить код"))
        self.send_pass.setText(_translate("Tg_panel", "Подтвердить"))
        self.guide_bots.setText(_translate("Tg_panel", "Как добавлять?"))

        self.label.setText(_translate("Tg_panel", "Номер телефона"))
        self.label_2.setText(_translate("Tg_panel", "Код подтверждения"))
        self.label_3.setText(_translate("Tg_panel", "Всего ботов подключено:"))

        self.sum_bots_2.setText(_translate("Tg_panel", "0"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Tg_panel", "Чаты"))
        self.add_chats.setText(_translate("Tg_panel", "Добавить чаты"))
        self.guide_chats.setText(_translate("Tg_panel", "Как добавлять?"))

        self.label_5.setText(_translate("Tg_panel", "Всего чатов в базе данных:"))

        self.sum_chat_bd.setText(_translate("Tg_panel", "0"))

    def btn_start_spam(self):
        print("Старт спама")

    def btn_sort_chats(self):
        print("сортировка")

    def btn_otpiska(self):
        print("отписка")

    def btn_podpiska(self):
        print("подписка")

    def btn_guide(self):
        print("гайд меню")

    def btn_send_pass(self):
        print("Подтвердить код")

    def btn_send_num(self):
        phone_number = self.phone_number.text()
        try:
            # Обрабатываем номер
            phone_number = int(phone_number)
            phone_number = str(phone_number)
            phone_number = '+' + phone_number
            print(phone_number)
            print(type(phone_number))

            # Открываем базу данных ботов
            try:
                with open("bots.json", "r", encoding="UTF-8") as f:
                    bots = json.loads(f.read())

            # Если его нет, то создаем переменную.
            except:
                bots = []

            # Проверка совпадений строк
            x = 0
            for bot in bots:
                if (phone_number == bot['number']):
                    x = 1

            # Сценарий найденого совпадения.
            if x == 1:
                self.info_box('Этот аккаунт уже есть в базе данных. Введите иной номер.')

            # Сценарий нового аккаунта
            else:
                # Создание сессии.
                with Client(name='x', in_memory=True, api_id=api_id, api_hash=api_hash, phone_number=phone_number) as app:
                    session_bot = app.export_session_string()
                    bots.append({
                        'number': phone_number,
                        'session': session_bot,
                        'time': 0,
                        'chats': 'None'
                    })
                    with open("bots.json", "w", encoding="UTF-8") as f:
                        f.write(json.dumps(bots, indent=4))



        except:
            # Выдаем ошибку формата и чистим поле
            self.phone_number.clear()
            self.warn_box('Введите номер телефона в формате 79001112233')

        print(f"доб бота {phone_number}")

    def btn_guide_bots(self):
        print("гайд бот")

    def btn_add_chats(self):
        self.chats_form.copy()
        self.chats_form.clear()
        print("доб чат")

    def btn_guide_chats(self):
        print("гайд чат")


    def warn_box(self, txt):
        warn_box = QMessageBox()
        warn_box.setWindowTitle("Ошибка")
        warn_box.setText(txt)
        warn_box.setIcon(QMessageBox.Warning)
        warn_box.exec_()
    def info_box(self, txt):
        warn_box = QMessageBox()
        warn_box.setWindowTitle("Информация")
        warn_box.setText(txt)
        warn_box.setIcon(QMessageBox.Warning)
        warn_box.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tg_panel = QtWidgets.QMainWindow()
    ui = Ui_Tg_panel()
    ui.setupUi(Tg_panel)
    Tg_panel.show()
    sys.exit(app.exec_())
